### PR TITLE
rename default file name

### PR DESCRIPTION
**Pull request by jqiuyin**
I guess main.yml is the default file of "include OS specific configuration",so I renamed it.  
Another suggestion:  
The default file should not contain any configuration, of course it's up to you.   
If you agree with this, I will modify it

### CODE REVIEW

**Comment by jqiuyin** [comment]
Is there any progress？

**Comment by bodsch** [comment]
Thank you very much for your PR.
I have just transferred it to the main branch.

**Comment by bodsch** [comment]
But it was not a good idea.
`vars/main.yml` is read in initially and thus defines all available variables, which are then overwritten by OS-specific ones if necessary.
`vars/default.yml` was originally a fallback for an unsupported OS.
I have now turned the PR back and removed the reference to `defaults.yml`.

**Comment by jqiuyin** [comment]
My original intention was to run it on centos.  
But if it encounters an incompatible system, it will report an error when running "include OS specific configuration"
I wish it could return an empty config if it encounters an unrecognized OS  
like this:
```
- name: Fetch OS dependent variables
  include_vars:
    file: '{{ item }}'
    name: 'os_vars'
  with_first_found:
    - files:
        - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.os_family }}.yml'
      skip: true
  tags: always
```
In this case,if the file does not exist, the task will be skipped.but in your role ,it will report an error because 'lookup' will return an empty dict '[]'.  
what's your opinion on this？

**Comment by bodsch** [comment]
This role does not support CentOS ...
But you could create a suitable file under `vars` and define the required variables.

**Comment by jqiuyin** [comment]
Thanks for your suggestion, my problem is solved

**Pull request merged**
