### PR TITLE
feat: allow custom includes

### PR DESCRIPTION
**Pull request by umaniteam**
allow custom includes

### CODE REVIEW

**Comment by bodsch** [comment]
Thanks for the PR @umaniteam!

It's simple, I'll definitely merge it.


The only question I ask myself is whether you shouldn't make sure beforehand that the custom includes are also available on the system.

And how do they get there?

**Comment by umaniteam** [comment]
I don't know how it would be possible.

Not checking lets someone deploy a file by another mean and still use it.

**Comment by bodsch** [comment]
> I don't know how it would be possible.
> 
> Not checking lets someone deploy a file by another mean and still use it.

I am trying to implement a check for this.

Maybe the dynamic creation of include files will also work?

Do you have an example for me of why you asked for the PR?

**Comment by umaniteam** [comment]
that's for a log server, listening on the network.

I need complex configuration the current system can't generate, linked to #4 :
```
source source_514_tls {
    network(
        transport("tls")
        port("514")
        max-connections(300)
        keep-alive(yes)
        tcp-keep-alive(yes)
        tls(
           # SSL Certificates which we have created in previous steps
           key-file("/etc/syslog-ng/ssl/cert.d/server.key")
           cert-file("/etc/syslog-ng/ssl/cert.d/server.crt")
           ca-dir("/etc/syslog-ng/ssl/ca.d/")
           peer_verify(required-trusted)
        )
    );
};
```

I'll try to work on an implementation in the future

**Comment by bodsch** [comment]
Thank you for the example!

But isn't it already possible after that?
I had started to define this via the configuration, but had not yet been able to test the rendering of the configuration sufficiently.

Maybe you can help me with this?

**Comment by bodsch** [comment]
hi @umaniteam !

I have taken up the topic again and created an extra test for it.
You are welcome to take a look at the branch and test it.

I would be very grateful for any feedback.

https://github.com/bodsch/ansible-syslog-ng/blob/main/molecule/server-clients/group_vars/syslog_server/vars.yml#L47-L64

**Comment by umaniteam** [comment]
Hello,

Just tested, works like a charm !

Thank you very much ! :+1:

**Pull request merged**
